/**
 * ============LICENSE_START====================================================
 * org.onap.aaf
 * ===========================================================================
 * Copyright (c) 2018 AT&T Intellectual Property. All rights reserved.
 * ===========================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 *      http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END====================================================
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.09 at 10:14:23 PM IST 
//


package org.onap.aaf.misc.rosetta.env;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="route" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="meth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="explicitErr" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * <p>
 * <p>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "route"
})
@XmlRootElement(name = "api")
public class Api {

    protected List<Api.Route> route;

    /**
     * Gets the value of the route property.
     * <p>
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the route property.
     * <p>
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoute().add(newItem);
     * </pre>
     * <p>
     * <p>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Api.Route }
     * <p>
     * <p>
     */
    public List<Api.Route> getRoute() {
        if (route == null) {
            route = new ArrayList<Api.Route>();
        }
        return this.route;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="meth" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="comments" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="expected" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="explicitErr" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * <p>
     * <p>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "meth",
        "path",
        "param",
        "desc",
        "comments",
        "contentType",
        "expected",
        "explicitErr"
    })
    public static class Route {

        @XmlElement(required = true)
        protected String meth;
        @XmlElement(required = true)
        protected String path;
        protected List<String> param;
        @XmlElement(required = true)
        protected String desc;
        protected List<String> comments;
        protected List<String> contentType;
        protected int expected;
        @XmlElement(type = Integer.class)
        protected List<Integer> explicitErr;

        /**
         * Gets the value of the meth property.
         * <p>
         * @return
         *     possible object is
         *     {@link String }
         * <p>
         */
        public String getMeth() {
            return meth;
        }

        /**
         * Sets the value of the meth property.
         * <p>
         * @param value
         *     allowed object is
         *     {@link String }
         * <p>
         */
        public void setMeth(String value) {
            this.meth = value;
        }

        /**
         * Gets the value of the path property.
         * <p>
         * @return
         *     possible object is
         *     {@link String }
         * <p>
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * <p>
         * @param value
         *     allowed object is
         *     {@link String }
         * <p>
         */
        public void setPath(String value) {
            this.path = value;
        }

        /**
         * Gets the value of the param property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the param property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParam().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * <p>
         * <p>
         */
        public List<String> getParam() {
            if (param == null) {
                param = new ArrayList<String>();
            }
            return this.param;
        }

        /**
         * Gets the value of the desc property.
         * <p>
         * @return
         *     possible object is
         *     {@link String }
         * <p>
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * <p>
         * @param value
         *     allowed object is
         *     {@link String }
         * <p>
         */
        public void setDesc(String value) {
            this.desc = value;
        }

        /**
         * Gets the value of the comments property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the comments property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getComments().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * <p>
         * <p>
         */
        public List<String> getComments() {
            if (comments == null) {
                comments = new ArrayList<String>();
            }
            return this.comments;
        }

        /**
         * Gets the value of the contentType property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentType property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentType().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * <p>
         * <p>
         */
        public List<String> getContentType() {
            if (contentType == null) {
                contentType = new ArrayList<String>();
            }
            return this.contentType;
        }

        /**
         * Gets the value of the expected property.
         * <p>
         */
        public int getExpected() {
            return expected;
        }

        /**
         * Sets the value of the expected property.
         * <p>
         */
        public void setExpected(int value) {
            this.expected = value;
        }

        /**
         * Gets the value of the explicitErr property.
         * <p>
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the explicitErr property.
         * <p>
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExplicitErr().add(newItem);
         * </pre>
         * <p>
         * <p>
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * <p>
         * <p>
         */
        public List<Integer> getExplicitErr() {
            if (explicitErr == null) {
                explicitErr = new ArrayList<Integer>();
            }
            return this.explicitErr;
        }

    }

}
