#!/bin/sh
######################################################################
# $RCSfile$ - $Revision$
# Copyright 2012 AT&T Intellectual Property. All rights reserved.
######################################################################
#!/bin/sh
exit 0