FROM rmannfv/aaf-base:xenial 
MAINTAINER AAF Team, AT&T 2018
ENV VERSION=${AAF_VERSION}

LABEL description="aaf_agent"
LABEL version=${AAF_VERSION}

COPY logs /opt/app/aaf_config/logs
COPY bin/client.sh /opt/app/aaf_config/bin/agent.sh
COPY bin/aaf-cadi*full.jar /opt/app/aaf_config/bin/
COPY public/*all.jks /opt/app/aaf_config/public/

ENTRYPOINT ["/bin/bash","/opt/app/aaf_config/bin/agent.sh"]
CMD []

