#!/bin/env bash

if [[ $# < 1 ]]; then
    echo "USAGE: run_batch ExpiryNotification|ApprNotify|JobChange|RoleExpiration|ValidateUsers"
    exit 1;
fi

JAVA_HOME=_JAVA_HOME_
AAF_CP="_ROOT_DIR_/etc"
for JAR in `find _ROOT_DIR_/lib -name *.jar` ; do
  AAF_CP="$AAF_CP:$JAR"
done

$JAVA_HOME/bin/java -cp $AAF_CP com.att.authz.Batch $*


