#!/bin/bash
JAVA_HOME=_JAVA_HOME_
PATH=${PATH}:${JAVA_HOME}/bin
ROOT_DIR=_ROOT_DIR_

cd $ROOT_DIR

CP=${ROOT_DIR}/etc
for FILE in `ls $ROOT_DIR/lib/*.jar`; do
  CP=$CP:$FILE
done

CMD="SyncV1V2 v1 v2" 
echo $CMD >> $ROOT_DIR/cronlog
date >> $ROOT_DIR/cronlog
$JAVA_HOME/bin/java -Xmx2048m -classpath $CP com.att.authz.Batch $CMD  >> $ROOT_DIR/cronlog
date >> $ROOT_DIR/cronlog
