#!/bin/bash
JAVA_HOME=_JAVA_HOME_
PATH=${PATH}:${JAVA_HOME}/bin
ROOT_DIR=_ROOT_DIR_
ENV_CONTEXT=_ENV_CONTEXT_

cd $ROOT_DIR

if [ ! -e "$ROOT_DIR/data/stage" ]; then
	mkdir -p $ROOT_DIR/data/stage
fi

if [ ! -e "$ROOT_DIR/data/$ENV_CONTEXT/stage" ]; then
	mkdir -p $ROOT_DIR/data/$ENV_CONTEXT
	ln -s $ROOT_DIR/data/stage $ROOT_DIR/data/$ENV_CONTEXT/stage
fi

CP=${ROOT_DIR}/etc
for FILE in `ls $ROOT_DIR/lib/*.jar`; do
  CP=$CP:$FILE
done

CMD="V1DataFile all"
echo $CMD >> $ROOT_DIR/cronlog
date >> $ROOT_DIR/cronlog
$JAVA_HOME/bin/java -Xmx2048m -classpath $CP com.att.authz.Batch $CMD  >> $ROOT_DIR/cronlog
date >> $ROOT_DIR/cronlog

cd $ROOT_DIR/data/stage
LATEST=`ls -tr v1*.dat | tail -1`
if [ "$LATEST" != "" ]; then
  > ../v1.lock
  cp -p $LATEST ../v1.dat
  rm ../v1.lock
fi

LATEST=`ls -tr v1*.skip | tail -1`
if [ "$LATEST" != "" ]; then
  cp -p $LATEST ../v1.skip
fi

for FILE in `ls v1* | grep -v .gz`; do
	gzip $FILE
done


